### ISSUE TITLE
Title extraction enhancement

### ISSUE THREAD

**Issue by ssheikholeslami** [EIT6/NIPS-Papers-Search-App#1]
Hey @nrigheriu , as you mentioned yourself, there seems to be a problem in title extraction at least for one paper - **"Distributed k-means and k-median Clustering on General Topologies"** - for which the extracted title is **"Distributed"**. Could you please go back and look for potential causes? This might be an issue with more papers.

PS. It's not that necessary for now - just in case you find any free time 😄

**Comment by nrigheriu** [comment]
I found the title as ",Distributed ," in the papers.csv file, you can search for it yourself. Therefore I don't think this is a bug and I don't have any idea on how to avoid this other than just removing this paper alltogether since it messes up some things

**Comment by ssheikholeslami** [comment]
Okay, so probably it's better to close this issue at least for now.
